name: Ship Release

on:
  push:
    tags:
      - "v*.*.*"   # matches tags like v0.1.0, v1.2.3

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '{{ cookiecutter.python_version }}'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/prod.in') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools
          pip-compile requirements/prod.in
          pip install -r requirements/prod.txt

      - name: Run migrations
        run: python manage.py migrate --noinput

      - name: Run tests before release
        run: pytest --cov=apps --cov-report=term-missing

      - name: Build release artifact
        run: |
          echo "Building release artifact..."
          tar -czf release-${{ github.ref_name }}.tar.gz .

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ github.ref_name }}
          path: release-${{ github.ref_name }}.tar.gz

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: release-${{ github.ref_name }}.tar.gz
